import type { CustomAgentSpec, LoadedTemplate, TemplateConfig } from "@/core/types";
import { resolveTools } from "@/tools";

/**
 * Custom agents.
 *
 * A premium customer points AgentStack at a SaaS they already pay for. The
 * platform reads that product's site and docs, generates an agent spec, and
 * ships it here as JSON in `CUSTOM_AGENT_SPEC`. From this file down, the
 * runtime cannot tell a generated agent from a built-in one — same loop, same
 * tools, same scheduler.
 */

let cached: CustomAgentSpec | null | undefined;

export function customSpec(): CustomAgentSpec | null {
  if (cached !== undefined) return cached;

  const raw = process.env.CUSTOM_AGENT_SPEC;
  if (!raw) {
    cached = null;
    return cached;
  }

  try {
    cached = JSON.parse(raw) as CustomAgentSpec;
  } catch (cause) {
    // A malformed spec must fail loudly at load rather than produce an agent
    // with no instructions that quietly does nothing on a schedule.
    throw new Error(
      `CUSTOM_AGENT_SPEC is not valid JSON: ${
        cause instanceof Error ? cause.message : String(cause)
      }`,
    );
  }
  return cached;
}

export function isCustomTemplate(id: string): boolean {
  return id === "custom-agent";
}

/** Builds a full template out of the generated spec. */
export function loadCustomTemplate(): LoadedTemplate {
  const spec = customSpec();
  if (!spec) {
    throw new Error(
      "ACTIVE_TEMPLATE is custom-agent but CUSTOM_AGENT_SPEC is not set. " +
        "Rebuild this agent from the dashboard.",
    );
  }

  const hasApi = Boolean(spec.api?.baseUrl);
  const toolNames = [
    "read_page",
    "draft",
    "list_prompts",
    "notify",
    ...(hasApi ? ["api_request"] : []),
  ];

  const config: TemplateConfig = {
    id: "custom-agent",
    name: spec.name,
    description: spec.description,
    category: "Custom",
    icon: "🧩",
    replaces: spec.replaces,
    frequency: "0 9 * * 1-5",
    model: process.env.AGENT_MODEL || "gpt-4o-mini",
    temperature: 0.6,
    maxIterations: 10,
    tools: toolNames,
    prompts: ["system"],
    scheduledTask: spec.scheduledTask,
    examples: spec.examples,
    settings: [],
    secrets: hasApi
      ? [{ key: "SERVICE_API_KEY", label: `${spec.name} API key`, required: true }]
      : [],
  };

  return {
    config,
    prompts: { system: buildSystemPrompt(spec) },
    tools: resolveTools("custom-agent", toolNames),
  };
}

function buildSystemPrompt(spec: CustomAgentSpec): string {
  const parts = [spec.systemPrompt];

  if (spec.api?.baseUrl) {
    parts.push(
      "\n## The API you control\n" +
        `Base URL: ${spec.api.baseUrl}\n` +
        "Call it with the `api_request` tool. Authentication is attached for " +
        "you — never ask the user for a key, never put one in your arguments, " +
        "and never repeat one back.",
    );

    if (spec.api.endpoints.length > 0) {
      parts.push(
        "Endpoints worth knowing:\n" +
          spec.api.endpoints
            .slice(0, 25)
            .map((e) => `- ${e.method.toUpperCase()} ${e.path} — ${e.purpose}`)
            .join("\n"),
      );
    }
  }

  parts.push(
    "\n## Honesty\n" +
      "This agent was generated by reading public documentation, which may be " +
      "out of date or incomplete. If an endpoint 404s or a field is missing, " +
      "say so plainly and report what you did learn. Never invent an API " +
      "response, a record, or a number.",
  );

  return parts.join("\n");
}
